add_newline = false

[line_break]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 5
style = 'blue'
read_only = ' '

[cmd_duration]
min_time = 30_000
format = "[$duration](yellow) "

[ruby]
format = '[\[$symbol$version\]]($style) '
symbol = ' '
style = 'green'

[python]
format = '[\[$symbol$version\]]($style) '
symbol = " "
style = 'green'

[git_branch]
symbol = ""
format = '[\[$symbol$branch\]]($style) '
style = "purple"

[aws]
disabled = true
symbol = " "

[dotnet]
disabled = true

[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
disabled = true
symbol = " "

[dart]
disabled = true
symbol = " "

[elixir]
disabled = true
symbol = " "

[elm]
disabled = true
symbol = " "

[git_commit]
disabled = true

[git_status]
disabled = true

[git_state]
disabled = true

[golang]
disabled = true
symbol = " "

[hg_branch]
disabled = true
symbol = " "

[java]
disabled = true
symbol = " "

[julia]
disabled = true
symbol = " "

[memory_usage]
disabled = true
symbol = " "

[nim]
disabled = true
symbol = " "

[nix_shell]
disabled = true
symbol = " "

[nodejs]
disabled = true
symbol = " "

[package]
disabled = true
symbol = " "

[perl]
disabled = true
symbol = " "

[php]
disabled = true
symbol = " "

[rust]
disabled = true
symbol = " "

[swift]
disabled = true
symbol = "ﯣ "
