[colors]
background = ${env:WISP_BACKGROUND_ARGB:#282828}
background-secondary = ${env:WISP_BACKGROUND_SECONDARY:#282828}
background-alt = #444
foreground = ${env:WISP_FOREGROUND:#ebdbb2}
foreground-alt = ${env:WISP_COLOR8:#555}

black = ${env:WISP_BACKGROUND:#282828}
red = ${env:WISP_COLOR9:#fb4934}
green = ${env:WISP_COLOR10:#b8bb26}
yellow = ${env:WISP_COLOR11:#fabd2f}
alt_blue = ${env:WISP_COLOR4:#4585dd}
blue = ${env:WISP_COLOR12:#83a598}
icon = ${env:WISP_FOREGROUND:#555}

[bar/default]
enable-ipc = true
width = 3420
offset-x = 10
offset-y = 10
height = 42
; radius = 10
fixed-center = true
bottom = false

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 5
line-color = #f00

border-size = 0
border-color = ${colors.foreground}

padding-left = 0
padding-right = 2

module-margin-left = 2
module-margin-right = 1

; font-0 = Inconsolata:weight=bold:size=11:antialias=true;1
font-0 = MonoLisa:weight=bold:size=9:antialias=true;2
font-1 = Font Awesome 6 Brands:size=10:antialias=true;2
font-2 = siji:size=12:antialias=true;1
font-3 = Font Awesome 6 Free:style=Solid:size=10:antialias=true;2
font-4 = Source Han Sans JP:size=11
font-5 = "waffle:size=12;2"
font-6 = "Noto Color Emoji:size=11:style=Regular:scale=11;2"
font-7 = hack:weight=bold:size=8:antialias=true;2

modules-left = xmonad playerctl
modules-center = xwindow
modules-right = cpu indicator services hue pulseaudio date

tray-position = right
tray-transparent = true
; tray-background = #ffffffff
tray-padding = 2
tray-reparent = false
tray-detached = false

override-redirect = false
wm-restack = generic
cursor-click = pointer
cursor-scroll = ns-resize

[module/cpu]
type = internal/cpu
label = %percentage%% CPU

[module/xwindow]
type = internal/xwindow
label = %title:0:50:…%

[module/date]
type = internal/date
interval = 5

date = ""
date-alt = " %Y-%m-%d"

time = "%H:%M"
time-alt = "%H:%M:%S"

format-prefix = 
format-prefix-foreground = ${colors.icon}
format-underline = 

label = %date% %time%

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <label-volume>
label-volume = %percentage%%
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.icon}
label-volume-foreground = ${root.foreground}

format-muted = <label-muted>
label-muted = %{F#555} %percentage%%
label-muted-foreground = #666

click-right = pavucontrol --name polybar-pavucontrol &
use-ui-max = false

format-muted-underline =
format-volume-underline =

[module/xmonad]
type = custom/script
exec = tail -F /tmp/workspace-info
exec-if = [ -p /tmp/workspace-info ]
tail = true

[module/playerctl]
type = custom/script
exec = ~/.config/polybar/scripts/polybar-playerctl
exec-if = true
tail = true
format = <label>

[module/hue]
type = custom/script
exec = ~/.config/polybar/scripts/polybar-hue
exec-if = true
tail = true
click-left = polybar-hue toggle
click-middle = polybar-hue next
click-right = polybar-hue change_color
scroll-up = polybar-hue increase
scroll-down = polybar-hue decrease

[module/indicator]
type = custom/script
exec = indicator
exec-if = true
tail = true

[module/services]
type = custom/script
exec = ~/.config/polybar/scripts/polybar-services sshd user:lstatus:ls user:streamdeckd:sd
exec-if = true
tail = true
label-font = 8

[settings]
screenchange-reload = true

[global/wm]
margin-top = 0
margin-bottom = 0
