#!/bin/sh
while true; do
    BATTERY_PERCENT="$(acpi | grep -oP '[[:digit:]]+(?=%)' | awk '{ sum += $1; } END { print sum; }')"
    BATTERY_COLOR="#859900"
    if [[ "$BATTERY_PERCENT" -lt "66" ]]; then
        BATTERY_COLOR="#b58900"
    fi;
    if [[ "$BATTERY_PERCENT" -lt "20" ]]; then
        BATTERY_COLOR="#dc322f"
    fi;

    BATTERY_BAR="$(echo $BATTERY_PERCENT 205 \
        | gdbar -w 25 -h 10 -s o -ss 0 -sw 1 -bg '#657b83' -fg $BATTERY_COLOR)"
    echo "^fg(#bbb)battery ^fg()$BATTERY_BAR $BATTERY_PERCENT%"

    sleep 10;
done;
