#!/bin/bash
# little dzen-thingy to control your volume
# you need amixer (or aumix) and gdbar
# (c) 2007 Tom Rauchenwald and Jochen Schweizer

BG='#212121'     # dzen backgrounad
FG='#888'     # dzen foreground
W=75         # width of the dzen bar
GW=48         #  width of the volume gauge
GFG='#0085e3' # color of the gauge
GFGM='#999'
GH=8          # height of the gauge
GBG='#657b83'    # color of gauge background
#X=560         # x position
X=1063
#Y=-1         # y position
Y=0

CARD=1
CHANNEL="Master"

# Caption of the gauge
# in this case it displays the volume icon shipped with dzen
#  CAPTION="^i(/home/sec/share/images/volume.xbm) "
CAPTION_ON="volume"
CAPTION_OFF="volume"
# Font to use
FN='-xos4-terminus-*-*-*-*-12-*-*-*-*-*-*-*'

# command to increase the volume
CI="amixer -c$CARD sset $CHANNEL 2dB+ >/dev/null"
# command to decrease the volume
CD="amixer -c$CARD sset $CHANNEL 2dB- >/dev/null"
#command to mute sound
MT="amixer -c$CARD sset $CHANNEL toggle >/dev/null"

# command to pipe into gdbar to display the gauge
# should print out 2 space-seperated values, the first is the current
# volume, the second the maximum volume
MAX=`amixer -c$CARD get $CHANNEL | awk '/^  Limits/ { print $5 }'`
MAX=$((MAX+5))
CV="amixer -c$CARD get $CHANNEL | awk '/^  Mono/ { print \$3 \" \" $MAX }'"
while true; do
    MC=`amixer -c$CARD get $CHANNEL | awk '/^  Mono/ { print $6 }'`
    if [ "$MC" = "[off]" ]; then
        echo -n "        ^fg(#bbb)$CAPTION_OFF "
        eval "$CV" | gdbar -s o -h $GH -w $GW -fg $GFGM -bg $GBG #-ss 1 -sw 1
    else
        echo -n "        ^fg(#bbb)$CAPTION_ON "
        eval "$CV" | gdbar -s o -h $GH -w $GW -fg $GFG -bg $GBG #-ss 1 -sw 1
    fi
    sleep 0.5;
done
