#!/bin/sh

HOST=heise.de

if ! ping=$(ping -c 1 -W 1 $HOST 2>/dev/null); then
    echo " %{F$XRDBCOLOR9}%{F-} ?? ms"
else
    rtt=$(echo "$ping" | sed -rn 's/.*time=([0-9]{1,})\.?[0-9]{0,} ms.*/\1/p')

    if [ "$rtt" -lt 30 ]; then
        icon="%{F$XRDBCOLOR10}%{F-}"
    elif [ "$rtt" -lt 75 ]; then
        icon="%{F$XRDBCOLOR11}%{F-}"
    else
        icon="%{F$XRDBCOLOR9}%{F-}"
    fi

    echo "$icon $rtt ms"
fi
